말 움직임 구현
upnl/finger-yutnori pull request #30
Opened 2024-02-06 11:27 UTC by aspective04

말의 움직임을 구현하고, 임시적으로 디버깅용 조작법을 추가하였습니다.

숫자키 1, 2, 3, 4, 5번을 누르면 그 값만큼 앞으로 움직이고, 0번을 누르면 뒤로 한 칸 움직입니다.

윷판을 한 바퀴 돌아 출발 지점에서 움직이려 시도하면 finished 변수가 true로 바뀌면서 움직이지 않게 됩니다.

실제로 구현할 때에는 StartMove(int totalDist) 함수를 이용해서 말이 totalDist 칸만큼 움직이게 할 수 있습니다.

2024-02-06 15:59 UTC, nick11967 commented
두 번째로 `Start()`와 `Update()`는 변수 선언보다는 아래로, 다른 함수들보다는 위로 옮깁시다. 전체적인 흐름을 보여주는 함수이기 때문에 가장 위에 적는 것이 좋을 것 같아요.

2024-02-06 16:05 UTC, nick11967 commented
마지막으로 1을 연속으로 눌렀을 때와 0을 연속으로 눌렀을 때 동작에 차이가 있습니다! 해보시고 왜 그런지 고민해보시면 금방 수정하실 수 있을 것 같아요.

코드 주석 달기랑 뒤로 가는 움직임에 대한 부분만 수정하면 완벽할 것 같네요. 수정해서 올려주세요~

2024-02-06 16:06 UTC, nick11967 requested changes
1. 코드에 주석 달기
2. 뒤로 움직임 수정하기

2024-02-07 08:49 UTC, aspective04 commented
피드백 반영하여 주석을 추가하고, Handle...()로 뭉뚱그려져 있던 함수들을 Check...()와 MoveFrom...() 함수로 쪼개서 조금 더 직관적으로 쓸 수 있게 했습니다. 그리고 아무 윷판 점 위에 있는지를 체크하는 IsOnBoardPoint() 함수를 추가하여 점 위에 정지해 있을 때에만 키보드 입력을 감지하거나 움직일 수 있게 했습니다.

2024-02-07 11:18 UTC, nick11967 commented on Assets/Scripts/Token/Token.cs
> +    private int movedDist;
변수에는 `<summary>`를 붙일 필요는 없어요. 
보통 변수는 수정 전처럼 적어주고 `//`만 이용해서 바로 옆에 주석을 적어주면 충분합니다.
그리고 문장으로 적어줬는데 요약해서 적어주면 더 좋을 것 같아요.

2024-02-07 11:20 UTC, nick11967 commented on Assets/Scripts/Token/Token.cs
> +    private bool finished;
```suggestion
    private int totalDist;    // Distance that token has to move on this turn; Negative values represent backward movement
    private int movedDist;    /// Distance that token has moved on this turn

    private Stack<Vector2> previousPositions;     /// Stores the token's previous positions for backward movement

    private bool finished;    /// Whether the token has completed a lap
```

2024-02-07 11:21 UTC, merged

2024-02-07 11:22 UTC, nick11967 commented
충분한 것 같아서 다음 작업 진행될 수 있도록 머지했습니다.