백도 구현 방법 변경 및 TokenManager 수정
upnl/finger-yutnori pull request #55
Opened 2024-02-13 12:06 UTC by aspective04

Token에서 previousPositions 스택을 삭제하고, 앞으로 움직일 때만 직전의 위치를 저장하는 previousPosition을 대신 넣었습니다.
Token마다 initialPosition을 따로 저장하도록 하였으며, previousPosition이 없을 때 null값으로 initialPosition을 사용했습니다.
previousPosition은 움직이기 시작할 때 initialPosition으로 초기화됩니다. 백도는 기본적으로 previousPosition으로 움직이나, 백도를 한 번 하면 previousPosition은 initialPosition으로 변경되어, 연속으로 백도를 하려고 하면 직선 경로 상의 뒤 지점으로 움직입니다.
이 외에도, 백도로 중앙에 갔다가 중앙에서 다시 백도 시 방향을 결정하기 위한 isFromLeftDiag 변수를 추가했습니다.

2024-02-15 23:54 UTC, nick11967 commented
좋아요 이제 기능도 잘 작동하고 코드도 정리가 된 것 같아요. 수고하셨습니다!
그런데 이전에 있었던 `GetNextPosition()` 과 이번 PR 중 만들었던 `GetPreviousPosition()` 이었나요? 이 함수들을 살리면 좋을 것 같습니다. 이유는 그 자체로 하나의 좋은 기능을 하고 다른 클래스에서도 사용할만한 함수이기 때문입니다.
약간 수정을 가해서 `public`으로 수정하고 `GetNextPosition(Vector2 pos, bool isFirstMove)`와 같이 다음 위치는 Token이 아닌 좌표로 계산할 수 있게 만들어봤으면 합니다.

2024-02-15 23:55 UTC, nick11967 requested changes
`GetNextPosition(Vector2 pos, bool isFirstMove)` 그리고 `GetPreviousPosition(Token token)`을 추가해보면 좋을 것 같습니다.

2024-02-18 08:16 UTC, nick11967 commented
`BoardPointIndex`를 TokenManger가 아닌 다른 새로운 파일에 넣고 사용하면 좋을 것 같습니다. static으로 만들면 바로 사용할 수 있을 것이다.

2024-02-18 13:43 UTC, aspective04 commented
token의 다음 위치에 해당하는 BoardPointIndex를 반환하는 GetNextIndex(Token token, bool isFirstMove),
token의 이전 위치(백도)에 해당하는 BoardPointIndex를 반환하는 GetPreviousIndex(Token token),
token이 distance만큼 움직인 위치를 반환하는 GetIndexAfterMove(Token token, int distance)를 추가했으며, 대부분의 함수를 public으로 변경했습니다.

Token이 한 바퀴를 돌았는지 확인하는 bool hasLooped를 추가하여,  시작점에서 백도를 쓸 때에 한 바퀴를 돌아서 왔다면 원래의 경로에서 뒤로 돌아가고, 그렇지 않다면 시작점으로 가기 이전의 초기 상태(Initial)로 가도록 하였습니다.

또한, Initial에서 StartMove()를 쓰면 시작점으로 움직이고 나서 입력한 거리만큼 움직이는 것까지를 자동으로 하도록 하였습니다.

앞에서 설명한 GetIndexAfterMove()를 구현하기 위해서는 EmptyToken 프리팹을 추가하여, 가상의 말을 InstantMoveTo()를 활용하여 주어진 거리만큼 움직인 후 그 위치의 인덱스를 반환하도록 하였습니다.

다만, 어떤 위치에서 다음 위치를 계산하려면 좌표뿐만 아니라 canFinish, hasLooped, routeType 등의 정보가 추가적으로 필요하여, Token을 입력받는 방식을 유지했습니다.

2024-02-18 14:25 UTC, nick11967 commented on Assets/Scripts/Managers/TokenManager.cs
>      private List<Token> tokens1, tokens2;
```suggestion
    public List<Token> tokens1, tokens2;
```

2024-02-18 14:27 UTC, nick11967 commented on Assets/Scripts/Managers/TokenManager.cs
>      private List<Token> tokens1, tokens2;
외부에서 다른 함수를 사용할 수는 있는데 결국 TokenManager의 token들이 필요한 것 같아요. 그래서 public으로 수정하였습니다. 이 부분에서 코드를 개선할 부분이 더 있을 수 있겠지만 지금은 다음 작업 진행을 위해서 머지하려고 합니다. 이런 부분에 대해서는 해당 작업을 하기 전 얘기를 나눠보고 진행하면 좋을 것 같습니다.

2024-02-18 14:28 UTC, merged